### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by verticalsync** [Lier0102/Lier0102#1]
I saw that you forked my readme before, and from looking at this I assume you copied some of the stuff, that's alright but about your discord activity stuff that you added in commit 94dc1bf it says user not found because you must be in their discord server, so it can get your data like online/offline, pfp, name etc here is an invite to the server if you'd like to join it: https://discord.gg/MqYMAb3TPN

**Comment by Lier0102** [comment]
thx
